stages:
  - testing
  - build development
  - bump production
  - build production

include:
  - local: .gitlab/ci/helm-binance-trading-bot.yml
  - local: .gitlab/ci/helm-ip-lookup.yml
  - local: .gitlab/ci/helm-woodle-map.yml
