{{- if and (eq .Values.database.type "postgres") (not .Values.database.postgres.external.enabled) .Values.database.postgres.internal.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}-postgres
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "n8n.labels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.database.postgres.internal.image.repository }}:{{ .Values.database.postgres.internal.image.tag }}"
          imagePullPolicy: {{ .Values.database.postgres.internal.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: "n8n"
            - name: POSTGRES_USER
              value: "n8n"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.database.postgres.internal.existingSecret }}
                  name: {{ .Values.database.postgres.internal.existingSecret }}
                  {{- else }}
                  name: {{ include "n8n.fullname" . }}-postgres
                  {{- end }}
                  key: password
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          {{- with .Values.database.postgres.internal.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "n8n" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "n8n" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
      {{- if .Values.database.postgres.internal.persistence.enabled }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "n8n.fullname" . }}-postgres-data
      {{- else }}
      volumes:
        - name: postgres-data
          emptyDir: {}
      {{- end }}
{{- end }}
