{{- if and .Values.redis.enabled (not .Values.redis.external.enabled) .Values.redis.internal.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}-redis
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "n8n.labels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      {{- with .Values.redis.internal.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: "{{ .Values.redis.internal.image.repository }}:{{ .Values.redis.internal.image.tag }}"
          imagePullPolicy: {{ .Values.redis.internal.image.pullPolicy }}
          {{- with .Values.redis.internal.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          {{- with .Values.redis.internal.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.redis.internal.persistence.enabled }}
            - name: redis-data
              mountPath: /data
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
      {{- if .Values.redis.internal.persistence.enabled }}
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ include "n8n.fullname" . }}-redis-data
      {{- else }}
      volumes:
        - name: redis-data
          emptyDir: {}
      {{- end }}
{{- end }}
