{{- if and .Values.redis.enabled (not .Values.redis.external.enabled) .Values.redis.internal.enabled .Values.redis.internal.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "n8n.fullname" . }}-redis-data
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.internal.persistence.size }}
  {{- if .Values.redis.internal.persistence.storageClass }}
  storageClassName: {{ .Values.redis.internal.persistence.storageClass }}
  {{- end }}
{{- end }}
