# If redis.enabled === true + redis.external.enabled === true + redis.external.existingSecret !== "", and redis.external.password !== "",
# then create a secret for the redis password
{{- if and .Values.redis.enabled .Values.redis.external.enabled (not .Values.redis.external.existingSecret) .Values.redis.external.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-redis-external
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  password: {{ .Values.redis.external.password | b64enc | quote }}
{{- end }}
