# If database type is postgres and internal is enabled, create a secret for the postgres password
{{- if and (eq .Values.database.type "postgres") (not .Values.database.postgres.external) .Values.database.postgres.internal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-postgres
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
data:
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
