# If database.type === postgres + postgres.external.enabled === true + postgres.external.existingSecret === "" + postgres.external.password !== "", then create a secret for the postgres password for postgres.external.password
{{- if and (eq .Values.database.type "postgres") .Values.database.postgres.external.enabled (not .Values.database.postgres.external.existingSecret) (not .Values.database.postgres.external.password) }}
{{- fail "database.postgres.external.password is required when existingSecret is not provided" }}
{{- end }}
{{- if .Values.database.postgres.external.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-postgres-external
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
data:
  password: {{ .Values.database.postgres.external.password | b64enc | quote }}
{{- end }}

