{{- if or .Values.encryption.key (and (eq .Values.database.type "postgres") .Values.database.postgres.external.enabled .Values.database.postgres.password) (and .Values.redis.enabled .Values.redis.external.enabled .Values.redis.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-secrets
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.encryption.key }}
  encryptionKey: {{ .Values.encryption.key | b64enc | quote }}
  {{- end }}
  # If database type is postgres and external is enabled, create a secret for the postgres password
  {{- if and (eq .Values.database.type "postgres") .Values.database.postgres.external.enabled .Values.database.postgres.password }}
  externalDatabasePassword: {{ .Values.database.postgres.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.redis.enabled .Values.redis.external.enabled .Values.redis.password }}
  redisPassword: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
{{- end }}
