# If redis is enabled and external is enabled, create a secret for the redis password if existingSecret is not provided
{{- if and .Values.redis.enabled .Values.redis.external.enabled (not .Values.redis.external.existingSecret) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-redis" (include "n8n.fullname" .)) }}
{{- $password := "" }}
{{- if $existingSecret }}
  {{- $password = index $existingSecret.data "password" }}
{{- else }}
  {{- $password = randAlphaNum 32 | b64enc }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-redis
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  password: {{ $password | quote }}
{{- end }}
