# If database.type === postgres + postgres.internal.enabled === true + postgres.internal.existingSecret === "" + postgres.internal.password !== "", then create a secret for the postgres password for postgres.internal.password
{{- if and (eq .Values.database.type "postgres") .Values.database.postgres.internal.enabled (not .Values.database.postgres.internal.existingSecret) (not .Values.database.postgres.internal.password) }}
{{- fail "database.postgres.internal.password is required when existingSecret is not provided" }}
{{- end }}
{{- if .Values.database.postgres.internal.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-postgres-internal
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
data:
  password: {{ .Values.database.postgres.internal.password | b64enc | quote }}
{{- end }}
