# If encryption.key !== "", then create a secret for the encryption key
{{- if and (not .Values.encryption.existingSecret) (not .Values.encryption.key) }}
{{- fail "encryption.existingSecret or encryption.key is required" }}
{{- end }}
{{- if .Values.encryption.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-encryption
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: encryption
type: Opaque
data:
  encryptionKey: {{ .Values.encryption.key | b64enc | quote }}
{{- end }}
