{{- if not .Values.redis.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "binance-trading-bot.fullname" . }}-redis-secret
  labels:
    {{- include "binance-trading-bot.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.redis.secrets.password | b64enc | quote }}
{{- end }}
