{{- if not .Values.binanceBot.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "binance-trading-bot.fullname" . }}-secrets
  labels:
    {{- include "binance-trading-bot.labels" . | nindent 4 }}
type: Opaque
data:
  BINANCE_LIVE_API_KEY: {{ .Values.binanceBot.config.binance.live.apiKey | b64enc | quote }}
  BINANCE_LIVE_SECRET_KEY: {{ .Values.binanceBot.config.binance.live.secretKey | b64enc | quote }}
  BINANCE_TEST_API_KEY: {{ .Values.binanceBot.config.binance.test.apiKey | b64enc | quote }}
  BINANCE_TEST_SECRET_KEY: {{ .Values.binanceBot.config.binance.test.secretKey | b64enc | quote }}
{{- end }}
