apiVersion: v1
kind: Service
metadata:
  name: {{ include "binance-trading-bot.fullname" . }}-redis
  labels:
    {{- include "binance-trading-bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "binance-trading-bot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
