apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-server-boilerplate.fullname" . }}-storage-secret
  labels:
    {{- include "mcp-server-boilerplate.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
type: Opaque
data:
  {{- if .Values.valkey.auth.enabled }}
  MCP_CONFIG_STORAGE_VALKEY_URL: {{ printf "valkey://:%s@%s-valkey:6379" (.Values.valkey.auth.password | toString) (include "mcp-server-boilerplate.fullname" .) | b64enc | quote }}
  {{- else }}
  MCP_CONFIG_STORAGE_VALKEY_URL: {{ printf "valkey://%s-valkey:6379" (include "mcp-server-boilerplate.fullname" .) | b64enc | quote }}
  {{- end }}

