{{- if not .Values.valkey.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-server-boilerplate.fullname" . }}-valkey-secret
  labels:
    {{- include "mcp-server-boilerplate.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
type: Opaque
data:
  {{- if .Values.valkey.auth.enabled }}
  password: {{ include "mcp-server-boilerplate.valkeyPassword" . | b64enc | quote }}
  {{- end }}
{{- end }}